// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package messages

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ProductsFetcherClient is the client API for ProductsFetcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductsFetcherClient interface {
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type productsFetcherClient struct {
	cc grpc.ClientConnInterface
}

func NewProductsFetcherClient(cc grpc.ClientConnInterface) ProductsFetcherClient {
	return &productsFetcherClient{cc}
}

func (c *productsFetcherClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, "/messages.ProductsFetcher/Fetch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsFetcherClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/messages.ProductsFetcher/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductsFetcherServer is the server API for ProductsFetcher service.
// All implementations must embed UnimplementedProductsFetcherServer
// for forward compatibility
type ProductsFetcherServer interface {
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	mustEmbedUnimplementedProductsFetcherServer()
}

// UnimplementedProductsFetcherServer must be embedded to have forward compatible implementations.
type UnimplementedProductsFetcherServer struct {
}

func (UnimplementedProductsFetcherServer) Fetch(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedProductsFetcherServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedProductsFetcherServer) mustEmbedUnimplementedProductsFetcherServer() {}

// UnsafeProductsFetcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductsFetcherServer will
// result in compilation errors.
type UnsafeProductsFetcherServer interface {
	mustEmbedUnimplementedProductsFetcherServer()
}

func RegisterProductsFetcherServer(s grpc.ServiceRegistrar, srv ProductsFetcherServer) {
	s.RegisterService(&_ProductsFetcher_serviceDesc, srv)
}

func _ProductsFetcher_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsFetcherServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.ProductsFetcher/Fetch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsFetcherServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductsFetcher_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsFetcherServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.ProductsFetcher/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsFetcherServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductsFetcher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "messages.ProductsFetcher",
	HandlerType: (*ProductsFetcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _ProductsFetcher_Fetch_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ProductsFetcher_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/messages/messages.proto",
}
